name: Publish Docker images
on:
  push:
    branches:
        - master
jobs:
  pandoc:
    name: Push Pandoc Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build and Publish latest Docker image
      uses: VaultVulp/gp-docker-action@1.1.7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }} 
        image-name: pandoc
        dockerfile: pandoc/Dockerfile

